-- ============================================
-- 数据库重置脚本
-- 执行此脚本会删除所有表和数据，请谨慎操作！
-- 执行完后再执行 init.sql 重新初始化
-- ============================================

-- 关闭外键约束检查
SET CONSTRAINTS ALL DEFERRED;

-- 删除所有表（按依赖关系倒序删除）
DROP TABLE IF EXISTS "email_verification" CASCADE;
DROP TABLE IF EXISTS "book_note" CASCADE;
DROP TABLE IF EXISTS "reading_progress" CASCADE;
DROP TABLE IF EXISTS "book_chapter" CASCADE;
DROP TABLE IF EXISTS "book" CASCADE;
DROP TABLE IF EXISTS "book_category" CASCADE;
DROP TABLE IF EXISTS "login_log" CASCADE;
DROP TABLE IF EXISTS "Visitor" CASCADE;
DROP TABLE IF EXISTS "SiteConfig" CASCADE;
DROP TABLE IF EXISTS "Music" CASCADE;
DROP TABLE IF EXISTS "BookmarkSite" CASCADE;
DROP TABLE IF EXISTS "BookmarkCategory" CASCADE;
DROP TABLE IF EXISTS "FriendLink" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;
DROP TABLE IF EXISTS "Photo" CASCADE;
DROP TABLE IF EXISTS "Album" CASCADE;
DROP TABLE IF EXISTS "ChatterComment" CASCADE;
DROP TABLE IF EXISTS "Chatter" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "Comment" CASCADE;
DROP TABLE IF EXISTS "GitHubUser" CASCADE;
DROP TABLE IF EXISTS "PostTag" CASCADE;
DROP TABLE IF EXISTS "Post" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

-- 重置自增序列（可选，确保 id 从 1 开始）
DROP SEQUENCE IF EXISTS "user_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Category_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Tag_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Post_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "GitHubUser_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Comment_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Message_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Chatter_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "ChatterComment_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Album_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Photo_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Project_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "FriendLink_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "BookmarkCategory_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "BookmarkSite_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Music_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "SiteConfig_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Visitor_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "login_log_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "book_category_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "book_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "book_chapter_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "reading_progress_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "book_note_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "email_verification_id_seq" CASCADE;

-- 重新开启外键约束检查
SET CONSTRAINTS ALL IMMEDIATE;

-- 执行完成后，再执行 init.sql 重新初始化数据库
